# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AutoSplineDialog
                                 A QGIS plugin
 spline points
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 
        git sha              : :%H$
        copyright            : (C) 2021 by XiaolongChen
        email                : chenxiaolong@mogoauto.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__auth__ = 'A.Star'
